#!/bin/bash
 
IFS=$'\n'
echo -n ‘Owner: ‘
read own

while [ -z $own ]
do
    echo Owner is empty. Please try again.
    echo -n ‘Owner: ‘
    read own
done


echo -n ‘Repository: ‘
read rep

while [ -z $rep ]
do
   echo Repository is empty. Please try again.
   echo -n ‘Repository: ‘
   read rep

done


cd "`dirname "$0"`"

python TestP.py $own $rep

exit 




